@startuml 
title Chez Huong — Package Diagram

skinparam defaultFontName Monospace

package "Recipes Module" as Recipes {
    package "Application Layer" as RAL {
        package "Commands" as RecipesCommands {
            [CreateRecipeHandler]
        }
        package "Queries" as RecipesQueries {
            [GetRecipeHandler]
            [GetRecipesHandler]
        }
        package "Services" {
            [RecipesService]
            [IngredientService]
            [NutritionalValueService]
        }
    }

    package "Domain Layer" as RDL {
        package "Entities" {
            [Recipe]
            [Ingredient]
        }
        package "Ports" {
            [IRecipesRepository]
            [IIngredientRepository]
            [USDAPort]
        }
    }

    package "Infrastructure Layer" as RIL {
        package "Adapters" {
            package "Persistence" {
                [PrismaRecipesRepository]
                [PrismaIngredientRepository]
                [RecipeMapper]
            }
            package "External" {
                [USDAAdapter]
            }
        }
        package "Controllers" {
            [RecipesController]
            [IngredientController]

            package "DTOs" {
                [CreateRecipeDTO]
            }
        }
    }

    ' Internal flows
    RAL --> RDL: depends on
    RIL --> RAL: triggers
    RIL --> RDL: implements ports

    RecipesController --> RecipesService: uses
    RecipesController <-- NutritionalValueService: calculates
    RecipesService --> RecipesCommands: triggers
    RecipesService --> RecipesQueries: triggers
    RecipesCommands --> IRecipesRepository : depends on
    RecipesQueries --> IRecipesRepository : depends on
    PrismaRecipesRepository ..|> IRecipesRepository: implements (realizes)
    USDAAdapter ..|> USDAPort: implements (realizes)
}

package "Users Module" as Users {
    package "Application Layer" {
        rectangle "UserService" as UserService
    }

    package "Domain Layer" {
        rectangle "..." as ddots
    }

    package "Infrastructure Layer" {
        rectangle "..." as idots
    }
}

package "Auth Module" as Auth {
    package "Guards" as AuthGuards{
        [LocalAuthGuard]
        [JwtAuthGuard]
        [RolesGuard]
    }

    package "Strategies" as AuthStrategies {
        [LocalStrategy]
        [JwtStrategy]
    }

    package "Decorators" as AuthDecorators {
        [RolesDecorator]
    }

    component "AuthController" as AuthController
    component "AuthService" as AuthService

    AuthController --> AuthGuards:  uses
    AuthController --> AuthService: uses
    AuthService --> UserService: uses
    AuthGuards --> AuthStrategies: extends
    AuthDecorators --> AuthGuards: sets the metadata
}

package "Translation Module" as Translation {
    package "Application Layer" as TranslationAL {
        rectangle "TranslationService" as TranslationService
    }

    package "Domain Layer" as TranslationDL {
        rectangle "TranslationPort" as TranslationPort
    }

    package "Infrastructure Layer" as TranslationIL {
        rectangle "GoogleTranslateAdapter" as GoogleTranslateAdapter
        [TranslationController]
    }

    TranslationPort ..|> GoogleTranslateAdapter: implements (realizes)
    TranslationService --> TranslationPort: depends on
    TranslationController --> TranslationService: uses
}

package "Social & Interactions Module" as Social {
    package "Application Layer" as SocialAL {
        rectangle "SocialInteractionService" as SocialInteractionService
        [socialInteractionCommands]
        [socialInteractionQueries]

        SocialInteractionService --> socialInteractionCommands: depends on
        SocialInteractionService --> socialInteractionQueries: depends on
    }

    package "Domain Layer" as SocialDL {
        package "Entities" as SocialInteractionDL {
            [Comment]
            [Like]
        }
        package "Ports" as SocialInteractionDP {
            [SocialInteractionPort]
        }
    }

    package "Infrastructure Layer" as SocialIL {
        package "Adapters" as SocialILAdapters {
            package "Persistence" as SocialILPersistence {
                [PrismaSocialInteractionRepository]
            }
        }
        package "Controllers" as SocialILControllers {
            [SocialInteractionController]
        }
    }

    PrismaSocialInteractionRepository ..|> SocialInteractionPort: implements (realizes)
}

package "Audit Module" as Audit {
    [...] as AuditDots
}

' Dependencies
Users --> Recipes: Read/Write
Recipes --> Translation: Read
Users --> Social: Interactions
Social --> Recipes: Comments, Likes


@enduml