export enum AuditAction {
    // Auth
    USER_LOGIN = 'USER_LOGIN',
    // Recipes
    RECIPE_CREATED = 'RECIPE_CREATED',
    RECIPE_UPDATED = 'RECIPE_UPDATED',
    RECIPE_DELETED = 'RECIPE_DELETED',
    // Social
    RECIPE_LIKED = 'RECIPE_LIKED',
    RECIPE_UNLIKED = 'RECIPE_UNLIKED',
    COMMENT_ADDED = 'COMMENT_ADDED',
    COMMENT_DELETED = 'COMMENT_DELETED',
}
